-- AlterTable
ALTER TABLE "Task" ALTER COLUMN "remind_me" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "duedate" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updatedAt" DROP DEFAULT,
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(3);
